<a href="https://colab.research.google.com/github/PsicoJazz/Ciencia-de-Dados/blob/main/redesNeurais_Faren.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import pandas as pd

In [ ]:
def celcius_to_fahrenheit(celcius):
    return (1.8 * celcius + 32)

### Conversão de 60 graus Celsius para Fahrenheit

In [ ]:
temp_celcius = [-10, 20, 100]
temp_fare = [celcius_to_fahrenheit(temp) for temp in temp_celcius]

In [ ]:
df = pd.DataFrame({'celcius': temp_celcius, 'fare': temp_fare})
df

   celcius   fare
0      -10   14.0
1       20   68.0
2      100  212.0

In [ ]:
x = torch.FloatTensor(df['celcius'].values).unsqueeze(1) # Garante que x tenha a forma (batch_size, 1)
y = torch.FloatTensor(df['fare'].values).unsqueeze(1)

In [ ]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_layer = nn.Linear(in_features=1, out_features=1, bias=True)

    def forward(self, x):
        out = self.input_layer(x)
        return out

In [ ]:
EPOCHS = 1000
LR = 0.2

In [ ]:
model = Model()
criterion = nn.MSELoss()
optmizer = torch.optim.Adam(params=model.parameters(), lr=LR)

In [ ]:
weights = []
bias = []

for epoch in range(EPOCHS):
  output = model.forward(x)
  loss = criterion(output, y)
  optmizer.zero_grad()
  loss.backward()
  optmizer.step()

  weights.append(model.input_layer.weight.item())
  bias.append(model.input_layer.bias.item())

  print(f'Peso: {model.input_layer.weight.item():.2f}')
  print(f'Bias: {model.input_layer.bias.item():.2f}')

Peso: 0.42
Bias: 0.20
Peso: 0.62
Bias: 0.40
Peso: 0.82
Bias: 0.60
Peso: 1.01
Bias: 0.79
Peso: 1.20
Bias: 0.99
Peso: 1.39
Bias: 1.18
Peso: 1.57
Bias: 1.36
Peso: 1.74
Bias: 1.54
Peso: 1.90
Bias: 1.72
Peso: 2.05
Bias: 1.89
Peso: 2.19
Bias: 2.05
Peso: 2.31
Bias: 2.20
Peso: 2.41
Bias: 2.34
Peso: 2.50
Bias: 2.48
Peso: 2.56
Bias: 2.60
Peso: 2.61
Bias: 2.71
Peso: 2.64
Bias: 2.81
Peso: 2.65
Bias: 2.90
Peso: 2.65
Bias: 2.98
Peso: 2.63
Bias: 3.05
Peso: 2.60
Bias: 3.12
Peso: 2.56
Bias: 3.18
Peso: 2.52
Bias: 3.23
Peso: 2.46
Bias: 3.28
Peso: 2.40
Bias: 3.33
Peso: 2.34
Bias: 3.38
Peso: 2.28
Bias: 3.43
Peso: 2.22
Bias: 3.48
Peso: 2.16
Bias: 3.53
Peso: 2.10
Bias: 3.59
Peso: 2.05
Bias: 3.65
Peso: 2.01
Bias: 3.72
Peso: 1.97
Bias: 3.79
Peso: 1.94
Bias: 3.87
Peso: 1.91
Bias: 3.96
Peso: 1.90
Bias: 4.05
Peso: 1.89
Bias: 4.15
Peso: 1.89
Bias: 4.26
Peso: 1.89
Bias: 4.37
Peso: 1.90
Bias: 4.48
Peso: 1.92
Bias: 4.60
Peso: 1.94
Bias: 4.72
Peso: 1.96
Bias: 4.85
Peso: 1.98
Bias: 4.97
Peso: 2.01
Bias: 5.10
Peso: 2.04
Bias: 5.22
Peso: 2.06
Bias: 5.35
Peso: 2.09
Bias: 5.48
Peso: 2.11
Bias: 5.60
Peso: 2.12
Bias: 5.72
Peso: 2.14
Bias: 5.84
Peso: 2.15
Bias: 5.96
Peso: 2.16
Bias: 6.08
Peso: 2.16
Bias: 6.19
Peso: 2.16
Bias: 6.31
Peso: 2.16
Bias: 6.42
Peso: 2.15
Bias: 6.53
Peso: 2.14
Bias: 6.63
Peso: 2.13
Bias: 6.74
Peso: 2.12
Bias: 6.85
Peso: 2.10
Bias: 6.95
Peso: 2.09
Bias: 7.06
Peso: 2.08
Bias: 7.16
Peso: 2.06
Bias: 7.27
Peso: 2.05
Bias: 7.37
Peso: 2.04
Bias: 7.48
Peso: 2.03
Bias: 7.59
Peso: 2.02
Bias: 7.70
Peso: 2.02
Bias: 7.81
Peso: 2.02
Bias: 7.93
Peso: 2.01
Bias: 8.04
Peso: 2.01
Bias: 8.16
Peso: 2.02
Bias: 8.27
Peso: 2.02
Bias: 8.39
Peso: 2.02
Bias: 8.51
Peso: 2.03
Bias: 8.63
Peso: 2.03
Bias: 8.75
Peso: 2.04
Bias: 8.87
Peso: 2.04
Bias: 8.99
Peso: 2.05
Bias: 9.10
Peso: 2.05
Bias: 9.22
Peso: 2.05
Bias: 9.34
Peso: 2.05
Bias: 9.46
Peso: 2.05
Bias: 9.57
Peso: 2.05
Bias: 9.69
Peso: 2.05
Bias: 9.80
Peso: 2.05
Bias: 9.92
Peso: 2.05
Bias: 10.03
Peso: 2.05
Bias: 10.14
Peso: 2.04
Bias: 10.26
Peso: 2.04
Bias: 10.37
Peso: 2.03
Bias: 10.48
Peso: 2.03
Bias: 10.59
Peso: 2.03
Bias: 10.70
Peso: 2.02
Bias: 10.82
Peso: 2.02
Bias: 10.93
Peso: 2.02
Bias: 11.04
Peso: 2.01
Bias: 11.15
Peso: 2.01
Bias: 11.27
Peso: 2.01
Bias: 11.38
Peso: 2.01
Bias: 11.49
Peso: 2.01
Bias: 11.60
Peso: 2.01
Bias: 11.72
Peso: 2.01
Bias: 11.83
Peso: 2.01
Bias: 11.94
Peso: 2.01
Bias: 12.06
Peso: 2.01
Bias: 12.17
Peso: 2.01
Bias: 12.28
Peso: 2.01
Bias: 12.39
Peso: 2.01
Bias: 12.50
Peso: 2.01
Bias: 12.62
Peso: 2.01
Bias: 12.73
Peso: 2.01
Bias: 12.84
Peso: 2.01
Bias: 12.95
Peso: 2.00
Bias: 13.06
Peso: 2.00
Bias: 13.17
Peso: 2.00
Bias: 13.28
Peso: 2.00
Bias: 13.38
Peso: 2.00
Bias: 13.49
Peso: 2.00
Bias: 13.60
Peso: 1.99
Bias: 13.71
Peso: 1.99
Bias: 13.82
Peso: 1.99
Bias: 13.92
Peso: 1.99
Bias: 14.03
Peso: 1.99
Bias: 14.14
Peso: 1.99
Bias: 14.24
Peso: 1.98
Bias: 14.35
Peso: 1.98
Bias: 14.46
Peso: 1.98
Bias: 14.56
Peso: 1.98
Bias: 14.67
Peso: 1.98
Bias: 14.78
Peso: 1.98
Bias: 14.88
Peso: 1.98
Bias: 14.99
Peso: 1.98
Bias: 15.09
Peso: 1.98
Bias: 15.20
Peso: 1.98
Bias: 15.30
Peso: 1.98
Bias: 15.40
Peso: 1.98
Bias: 15.51
Peso: 1.97
Bias: 15.61
Peso: 1.97
Bias: 15.71
Peso: 1.97
Bias: 15.81
Peso: 1.97
Bias: 15.92
Peso: 1.97
Bias: 16.02
Peso: 1.97
Bias: 16.12
Peso: 1.97
Bias: 16.22
Peso: 1.97
Bias: 16.32
Peso: 1.96
Bias: 16.42
Peso: 1.96
Bias: 16.52
Peso: 1.96
Bias: 16.62
Peso: 1.96
Bias: 16.72
Peso: 1.96
Bias: 16.82
Peso: 1.96
Bias: 16.92
Peso: 1.96
Bias: 17.02
Peso: 1.96
Bias: 17.11
Peso: 1.96
Bias: 17.21
Peso: 1.96
Bias: 17.31
Peso: 1.95
Bias: 17.41
Peso: 1.95
Bias: 17.50
Peso: 1.95
Bias: 17.60
Peso: 1.95
Bias: 17.69
Peso: 1.95
Bias: 17.79
Peso: 1.95
Bias: 17.89
Peso: 1.95
Bias: 17.98
Peso: 1.95
Bias: 18.07
Peso: 1.95
Bias: 18.17
Peso: 1.95
Bias: 18.26
Peso: 1.94
Bias: 18.36
Peso: 1.94
Bias: 18.45
Peso: 1.94
Bias: 18.54
Peso: 1.94
Bias: 18.63
Peso: 1.94
Bias: 18.72
Peso: 1.94
Bias: 18.82
Peso: 1.94
Bias: 18.91
Peso: 1.94
Bias: 19.00
Peso: 1.94
Bias: 19.09
Peso: 1.94
Bias: 19.18
Peso: 1.93
Bias: 19.27
Peso: 1.93
Bias: 19.36
Peso: 1.93
Bias: 19.44
Peso: 1.93
Bias: 19.53
Peso: 1.93
Bias: 19.62
Peso: 1.93
Bias: 19.71
Peso: 1.93
Bias: 19.80
Peso: 1.93
Bias: 19.88
Peso: 1.93
Bias: 19.97
Peso: 1.93
Bias: 20.05
Peso: 1.93
Bias: 20.14
Peso: 1.92
Bias: 20.23
Peso: 1.92
Bias: 20.31
Peso: 1.92
Bias: 20.40
Peso: 1.92
Bias: 20.48
Peso: 1.92
Bias: 20.56
Peso: 1.92
Bias: 20.65
Peso: 1.92
Bias: 20.73
Peso: 1.92
Bias: 20.81
Peso: 1.92
Bias: 20.89
Peso: 1.92
Bias: 20.98
Peso: 1.92
Bias: 21.06
Peso: 1.91
Bias: 21.14
Peso: 1.91
Bias: 21.22
Peso: 1.91
Bias: 21.30
Peso: 1.91
Bias: 21.38
Peso: 1.91
Bias: 21.46
Peso: 1.91
Bias: 21.54
Peso: 1.91
Bias: 21.61
Peso: 1.91
Bias: 21.69
Peso: 1.91
Bias: 21.77
Peso: 1.91
Bias: 21.85
Peso: 1.91
Bias: 21.93
Peso: 1.91
Bias: 22.00
Peso: 1.90
Bias: 22.08
Peso: 1.90
Bias: 22.15
Peso: 1.90
Bias: 22.23
Peso: 1.90
Bias: 22.30
Peso: 1.90
Bias: 22.38
Peso: 1.90
Bias: 22.45
Peso: 1.90
Bias: 22.53
Peso: 1.90
Bias: 22.60
Peso: 1.90
Bias: 22.67
Peso: 1.90
Bias: 22.75
Peso: 1.90
Bias: 22.82
Peso: 1.90
Bias: 22.89
Peso: 1.90
Bias: 22.96
Peso: 1.89
Bias: 23.03
Peso: 1.89
Bias: 23.10
Peso: 1.89
Bias: 23.17
Peso: 1.89
Bias: 23.24
Peso: 1.89
Bias: 23.31
Peso: 1.89
Bias: 23.38
Peso: 1.89
Bias: 23.45
Peso: 1.89
Bias: 23.52
Peso: 1.89
Bias: 23.59
Peso: 1.89
Bias: 23.66
Peso: 1.89
Bias: 23.72
Peso: 1.89
Bias: 23.79
Peso: 1.89
Bias: 23.86
Peso: 1.89
Bias: 23.92
Peso: 1.88
Bias: 23.99
Peso: 1.88
Bias: 24.05
Peso: 1.88
Bias: 24.12
Peso: 1.88
Bias: 24.18
Peso: 1.88
Bias: 24.25
Peso: 1.88
Bias: 24.31
Peso: 1.88
Bias: 24.37
Peso: 1.88
Bias: 24.44
Peso: 1.88
Bias: 24.50
Peso: 1.88
Bias: 24.56
Peso: 1.88
Bias: 24.62
Peso: 1.88
Bias: 24.69
Peso: 1.88
Bias: 24.75
Peso: 1.88
Bias: 24.81
Peso: 1.88
Bias: 24.87
Peso: 1.87
Bias: 24.93
Peso: 1.87
Bias: 24.99
Peso: 1.87
Bias: 25.05
Peso: 1.87
Bias: 25.11
Peso: 1.87
Bias: 25.17
Peso: 1.87
Bias: 25.22
Peso: 1.87
Bias: 25.28
Peso: 1.87
Bias: 25.34
Peso: 1.87
Bias: 25.40
Peso: 1.87
Bias: 25.45
Peso: 1.87
Bias: 25.51
Peso: 1.87
Bias: 25.56
Peso: 1.87
Bias: 25.62
Peso: 1.87
Bias: 25.68
Peso: 1.87
Bias: 25.73
Peso: 1.87
Bias: 25.79
Peso: 1.87
Bias: 25.84
Peso: 1.86
Bias: 25.89
Peso: 1.86
Bias: 25.95
Peso: 1.86
Bias: 26.00
Peso: 1.86
Bias: 26.05
Peso: 1.86
Bias: 26.11
Peso: 1.86
Bias: 26.16
Peso: 1.86
Bias: 26.21
Peso: 1.86
Bias: 26.26
Peso: 1.86
Bias: 26.31
Peso: 1.86
Bias: 26.36
Peso: 1.86
Bias: 26.41
Peso: 1.86
Bias: 26.46
Peso: 1.86
Bias: 26.51
Peso: 1.86
Bias: 26.56
Peso: 1.86
Bias: 26.61
Peso: 1.86
Bias: 26.66
Peso: 1.86
Bias: 26.71
Peso: 1.86
Bias: 26.76
Peso: 1.85
Bias: 26.80
Peso: 1.85
Bias: 26.85
Peso: 1.85
Bias: 26.90
Peso: 1.85
Bias: 26.94
Peso: 1.85
Bias: 26.99
Peso: 1.85
Bias: 27.04
Peso: 1.85
Bias: 27.08
Peso: 1.85
Bias: 27.13
Peso: 1.85
Bias: 27.17
Peso: 1.85
Bias: 27.22
Peso: 1.85
Bias: 27.26
Peso: 1.85
Bias: 27.31
Peso: 1.85
Bias: 27.35
Peso: 1.85
Bias: 27.39
Peso: 1.85
Bias: 27.44
Peso: 1.85
Bias: 27.48
Peso: 1.85
Bias: 27.52
Peso: 1.85
Bias: 27.56
Peso: 1.85
Bias: 27.61
Peso: 1.85
Bias: 27.65
Peso: 1.85
Bias: 27.69
Peso: 1.85
Bias: 27.73
Peso: 1.84
Bias: 27.77
Peso: 1.84
Bias: 27.81
Peso: 1.84
Bias: 27.85
Peso: 1.84
Bias: 27.89
Peso: 1.84
Bias: 27.93
Peso: 1.84
Bias: 27.97
Peso: 1.84
Bias: 28.01
Peso: 1.84
Bias: 28.04
Peso: 1.84
Bias: 28.08
Peso: 1.84
Bias: 28.12
Peso: 1.84
Bias: 28.16
Peso: 1.84
Bias: 28.20
Peso: 1.84
Bias: 28.23
Peso: 1.84
Bias: 28.27
Peso: 1.84
Bias: 28.31
Peso: 1.84
Bias: 28.34
Peso: 1.84
Bias: 28.38
Peso: 1.84
Bias: 28.41
Peso: 1.84
Bias: 28.45
Peso: 1.84
Bias: 28.48
Peso: 1.84
Bias: 28.52
Peso: 1.84
Bias: 28.55
Peso: 1.84
Bias: 28.59
Peso: 1.84
Bias: 28.62
Peso: 1.84
Bias: 28.66
Peso: 1.84
Bias: 28.69
Peso: 1.83
Bias: 28.72
Peso: 1.83
Bias: 28.75
Peso: 1.83
Bias: 28.79
Peso: 1.83
Bias: 28.82
Peso: 1.83
Bias: 28.85
Peso: 1.83
Bias: 28.88
Peso: 1.83
Bias: 28.91
Peso: 1.83
Bias: 28.95
Peso: 1.83
Bias: 28.98
Peso: 1.83
Bias: 29.01
Peso: 1.83
Bias: 29.04
Peso: 1.83
Bias: 29.07
Peso: 1.83
Bias: 29.10
Peso: 1.83
Bias: 29.13
Peso: 1.83
Bias: 29.16
Peso: 1.83
Bias: 29.19
Peso: 1.83
Bias: 29.22
Peso: 1.83
Bias: 29.24
Peso: 1.83
Bias: 29.27
Peso: 1.83
Bias: 29.30
Peso: 1.83
Bias: 29.33
Peso: 1.83
Bias: 29.36
Peso: 1.83
Bias: 29.38
Peso: 1.83
Bias: 29.41
Peso: 1.83
Bias: 29.44
Peso: 1.83
Bias: 29.47
Peso: 1.83
Bias: 29.49
Peso: 1.83
Bias: 29.52
Peso: 1.83
Bias: 29.54
Peso: 1.83
Bias: 29.57
Peso: 1.83
Bias: 29.60
Peso: 1.83
Bias: 29.62
Peso: 1.82
Bias: 29.65
Peso: 1.82
Bias: 29.67
Peso: 1.82
Bias: 29.70
Peso: 1.82
Bias: 29.72
Peso: 1.82
Bias: 29.75
Peso: 1.82
Bias: 29.77
Peso: 1.82
Bias: 29.79
Peso: 1.82
Bias: 29.82
Peso: 1.82
Bias: 29.84
Peso: 1.82
Bias: 29.86
Peso: 1.82
Bias: 29.89
Peso: 1.82
Bias: 29.91
Peso: 1.82
Bias: 29.93
Peso: 1.82
Bias: 29.96
Peso: 1.82
Bias: 29.98
Peso: 1.82
Bias: 30.00
Peso: 1.82
Bias: 30.02
Peso: 1.82
Bias: 30.04
Peso: 1.82
Bias: 30.06
Peso: 1.82
Bias: 30.09
Peso: 1.82
Bias: 30.11
Peso: 1.82
Bias: 30.13
Peso: 1.82
Bias: 30.15
Peso: 1.82
Bias: 30.17
Peso: 1.82
Bias: 30.19
Peso: 1.82
Bias: 30.21
Peso: 1.82
Bias: 30.23
Peso: 1.82
Bias: 30.25
Peso: 1.82
Bias: 30.27
Peso: 1.82
Bias: 30.29
Peso: 1.82
Bias: 30.31
Peso: 1.82
Bias: 30.33
Peso: 1.82
Bias: 30.34
Peso: 1.82
Bias: 30.36
Peso: 1.82
Bias: 30.38
Peso: 1.82
Bias: 30.40
Peso: 1.82
Bias: 30.42
Peso: 1.82
Bias: 30.44
Peso: 1.82
Bias: 30.45
Peso: 1.82
Bias: 30.47
Peso: 1.82
Bias: 30.49
Peso: 1.82
Bias: 30.51
Peso: 1.82
Bias: 30.52
Peso: 1.82
Bias: 30.54
Peso: 1.82
Bias: 30.56
Peso: 1.82
Bias: 30.57
Peso: 1.81
Bias: 30.59
Peso: 1.81
Bias: 30.61
Peso: 1.81
Bias: 30.62
Peso: 1.81
Bias: 30.64
Peso: 1.81
Bias: 30.65
Peso: 1.81
Bias: 30.67
Peso: 1.81
Bias: 30.68
Peso: 1.81
Bias: 30.70
Peso: 1.81
Bias: 30.71
Peso: 1.81
Bias: 30.73
Peso: 1.81
Bias: 30.74
Peso: 1.81
Bias: 30.76
Peso: 1.81
Bias: 30.77
Peso: 1.81
Bias: 30.79
Peso: 1.81
Bias: 30.80
Peso: 1.81
Bias: 30.82
Peso: 1.81
Bias: 30.83
Peso: 1.81
Bias: 30.84
Peso: 1.81
Bias: 30.86
Peso: 1.81
Bias: 30.87
Peso: 1.81
Bias: 30.88
Peso: 1.81
Bias: 30.90
Peso: 1.81
Bias: 30.91
Peso: 1.81
Bias: 30.92
Peso: 1.81
Bias: 30.94
Peso: 1.81
Bias: 30.95
Peso: 1.81
Bias: 30.96
Peso: 1.81
Bias: 30.97
Peso: 1.81
Bias: 30.99
Peso: 1.81
Bias: 31.00
Peso: 1.81
Bias: 31.01
Peso: 1.81
Bias: 31.02
Peso: 1.81
Bias: 31.04
Peso: 1.81
Bias: 31.05
Peso: 1.81
Bias: 31.06
Peso: 1.81
Bias: 31.07
Peso: 1.81
Bias: 31.08
Peso: 1.81
Bias: 31.09
Peso: 1.81
Bias: 31.10
Peso: 1.81
Bias: 31.11
Peso: 1.81
Bias: 31.13
Peso: 1.81
Bias: 31.14
Peso: 1.81
Bias: 31.15
Peso: 1.81
Bias: 31.16
Peso: 1.81
Bias: 31.17
Peso: 1.81
Bias: 31.18
Peso: 1.81
Bias: 31.19
Peso: 1.81
Bias: 31.20
Peso: 1.81
Bias: 31.21
Peso: 1.81
Bias: 31.22
Peso: 1.81
Bias: 31.23
Peso: 1.81
Bias: 31.24
Peso: 1.81
Bias: 31.25
Peso: 1.81
Bias: 31.26
Peso: 1.81
Bias: 31.27
Peso: 1.81
Bias: 31.27
Peso: 1.81
Bias: 31.28
Peso: 1.81
Bias: 31.29
Peso: 1.81
Bias: 31.30
Peso: 1.81
Bias: 31.31
Peso: 1.81
Bias: 31.32
Peso: 1.81
Bias: 31.33
Peso: 1.81
Bias: 31.34
Peso: 1.81
Bias: 31.34
Peso: 1.81
Bias: 31.35
Peso: 1.81
Bias: 31.36
Peso: 1.81
Bias: 31.37
Peso: 1.81
Bias: 31.38
Peso: 1.81
Bias: 31.39
Peso: 1.81
Bias: 31.39
Peso: 1.81
Bias: 31.40
Peso: 1.81
Bias: 31.41
Peso: 1.81
Bias: 31.42
Peso: 1.81
Bias: 31.42
Peso: 1.81
Bias: 31.43
Peso: 1.81
Bias: 31.44
Peso: 1.81
Bias: 31.45
Peso: 1.81
Bias: 31.45
Peso: 1.81
Bias: 31.46
Peso: 1.81
Bias: 31.47
Peso: 1.81
Bias: 31.47
Peso: 1.81
Bias: 31.48
Peso: 1.81
Bias: 31.49
Peso: 1.81
Bias: 31.49
Peso: 1.81
Bias: 31.50
Peso: 1.81
Bias: 31.51
Peso: 1.81
Bias: 31.51
Peso: 1.81
Bias: 31.52
Peso: 1.81
Bias: 31.53
Peso: 1.80
Bias: 31.53
Peso: 1.80
Bias: 31.54
Peso: 1.80
Bias: 31.55
Peso: 1.80
Bias: 31.55
Peso: 1.80
Bias: 31.56
Peso: 1.80
Bias: 31.56
Peso: 1.80
Bias: 31.57
Peso: 1.80
Bias: 31.57
Peso: 1.80
Bias: 31.58
Peso: 1.80
Bias: 31.59
Peso: 1.80
Bias: 31.59
Peso: 1.80
Bias: 31.60
Peso: 1.80
Bias: 31.60
Peso: 1.80
Bias: 31.61
Peso: 1.80
Bias: 31.61
Peso: 1.80
Bias: 31.62
Peso: 1.80
Bias: 31.62
Peso: 1.80
Bias: 31.63
Peso: 1.80
Bias: 31.63
Peso: 1.80
Bias: 31.64
Peso: 1.80
Bias: 31.64
Peso: 1.80
Bias: 31.65
Peso: 1.80
Bias: 31.65
Peso: 1.80
Bias: 31.66
Peso: 1.80
Bias: 31.66
Peso: 1.80
Bias: 31.67
Peso: 1.80
Bias: 31.67
Peso: 1.80
Bias: 31.68
Peso: 1.80
Bias: 31.68
Peso: 1.80
Bias: 31.69
Peso: 1.80
Bias: 31.69
Peso: 1.80
Bias: 31.69
Peso: 1.80
Bias: 31.70
Peso: 1.80
Bias: 31.70
Peso: 1.80
Bias: 31.71
Peso: 1.80
Bias: 31.71
Peso: 1.80
Bias: 31.71
Peso: 1.80
Bias: 31.72
Peso: 1.80
Bias: 31.72
Peso: 1.80
Bias: 31.73
Peso: 1.80
Bias: 31.73
Peso: 1.80
Bias: 31.73
Peso: 1.80
Bias: 31.74
Peso: 1.80
Bias: 31.74
Peso: 1.80
Bias: 31.74
Peso: 1.80
Bias: 31.75
Peso: 1.80
Bias: 31.75
Peso: 1.80
Bias: 31.76
Peso: 1.80
Bias: 31.76
Peso: 1.80
Bias: 31.76
Peso: 1.80
Bias: 31.77
Peso: 1.80
Bias: 31.77
Peso: 1.80
Bias: 31.77
Peso: 1.80
Bias: 31.78
Peso: 1.80
Bias: 31.78
Peso: 1.80
Bias: 31.78
Peso: 1.80
Bias: 31.78
Peso: 1.80
Bias: 31.79
Peso: 1.80
Bias: 31.79
Peso: 1.80
Bias: 31.79
Peso: 1.80
Bias: 31.80
Peso: 1.80
Bias: 31.80
Peso: 1.80
Bias: 31.80
Peso: 1.80
Bias: 31.81
Peso: 1.80
Bias: 31.81
Peso: 1.80
Bias: 31.81
Peso: 1.80
Bias: 31.81
Peso: 1.80
Bias: 31.82
Peso: 1.80
Bias: 31.82
Peso: 1.80
Bias: 31.82
Peso: 1.80
Bias: 31.82
Peso: 1.80
Bias: 31.83
Peso: 1.80
Bias: 31.83
Peso: 1.80
Bias: 31.83
Peso: 1.80
Bias: 31.83
Peso: 1.80
Bias: 31.84
Peso: 1.80
Bias: 31.84
Peso: 1.80
Bias: 31.84
Peso: 1.80
Bias: 31.84
Peso: 1.80
Bias: 31.85
Peso: 1.80
Bias: 31.85
Peso: 1.80
Bias: 31.85
Peso: 1.80
Bias: 31.85
Peso: 1.80
Bias: 31.86
Peso: 1.80
Bias: 31.86
Peso: 1.80
Bias: 31.86
Peso: 1.80
Bias: 31.86
Peso: 1.80
Bias: 31.86
Peso: 1.80
Bias: 31.87
Peso: 1.80
Bias: 31.87
Peso: 1.80
Bias: 31.87
Peso: 1.80
Bias: 31.87
Peso: 1.80
Bias: 31.87
Peso: 1.80
Bias: 31.88
Peso: 1.80
Bias: 31.88
Peso: 1.80
Bias: 31.88
Peso: 1.80
Bias: 31.88
Peso: 1.80
Bias: 31.88
Peso: 1.80
Bias: 31.88
Peso: 1.80
Bias: 31.89
Peso: 1.80
Bias: 31.89
Peso: 1.80
Bias: 31.89
Peso: 1.80
Bias: 31.89
Peso: 1.80
Bias: 31.89
Peso: 1.80
Bias: 31.89
Peso: 1.80
Bias: 31.90
Peso: 1.80
Bias: 31.90
Peso: 1.80
Bias: 31.90
Peso: 1.80
Bias: 31.90
Peso: 1.80
Bias: 31.90
Peso: 1.80
Bias: 31.90
Peso: 1.80
Bias: 31.91
Peso: 1.80
Bias: 31.91
Peso: 1.80
Bias: 31.91
Peso: 1.80
Bias: 31.91
Peso: 1.80
Bias: 31.91
Peso: 1.80
Bias: 31.91
Peso: 1.80
Bias: 31.91
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.92
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.93
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.94
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.95
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.96
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.97
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.98
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 31.99
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00
Peso: 1.80
Bias: 32.00

In [ ]:
training_data = pd.DataFrame({'Pesos': weights, 'Bias':bias})
training_data.to_csv('training_data.csv', index=False)

In [ ]:
training_data.head()

      Pesos      Bias
0  0.422183  0.197481
1  0.621292  0.396834
2  0.818744  0.595016
3  1.013613  0.791425
4  1.204794  0.985374

In [ ]:
celcius_input = 80
f_result = celcius_to_fahrenheit(celcius_input)
print(f'{celcius_input}°C é igual a {f_result}°F')

80°C é igual a 176.0°F